version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/app.dockerfile
    container_name: wepayout_app
    restart: unless-stopped
    depends_on:
      - web
      - database
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - wepayout_network
    environment:
      - COMPOSE_HTTP_TIMEOUT=200

  web:
    build:
      context: ./
      dockerfile: ./docker/web/web.dockerfile
    container_name: wepayout_web
    restart: unless-stopped
    tty: true
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - wepayout_network

  database:
    image: mysql:8
    container_name: wepayout_database
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${HOME}/docker-databases/wepayout-db:/var/lib/mysql
    networks:
      - wepayout_network
    command: --default-authentication-plugin=mysql_native_password

#Docker Networks
networks:
  wepayout_network:
    driver: bridge
